version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    networks:
      - app-network
  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-network
    ports:
      - 33061:3306

volumes:
  mysql-volume:
networks:
  app-network: